# Site settings
title: Muhd Jamaldin
email: jamalin.md@hotmail.com
url: https://md-khid.github.io/
description: "Test.Test.Test.Test.Test.Test"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket
    url: 
  - title: github
    url: https://md-khid.github.io/

# Build settings
markdown: kramdown
permalink: pretty
