# Site settings
title: Muhd Jamaldin
email: jamaldin.md@hotmail.com
url: https://md-khid.github.io/
description: "'An ounce of prevention is worth a pound of cure.' - Benjamin Franklin"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Muhd Jamaldin

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: inkedin.com/in/md-j
  - title: github
    url: https://github.com/Md-Khid

# Build settings
markdown: kramdown
permalink: pretty
